version: "3.9"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    restart: on-failure

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - DB_NAME=${DB_NAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_USER=${DB_USER}
        - DB_ROOT_PWD=${DB_ROOT_PWD}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    expose:
      - "3306"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 10s
      retries: 4
      start_period: 10s
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    expose:
      - "9000"
    restart: always

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/wordpress'
  mariadb:
    name: mariadb
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/mariadb'

networks:
  inception: