version: "3"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - wp
    restart: on-failure

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - wp
    env_file:
      - .env
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - wp
    expose:
      - "9000"
    restart: always

volumes:
  wordpress:
    driver: local
  mariadb:
    driver: local

networks:
  wp: