SET PASSWORD FOR 'root'@'localhost' = PASSWORD('root_pwd');
CREATE DATABASE IF NOT EXISTS db;
CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'pwd';
GRANT ALL PRIVILEGES ON db.* TO 'user'@'%' IDENTIFIED BY 'pwd';
FLUSH PRIVILEGES;
